#:kivy 1.0

#:include analog_clock.kv

GridLayout:
    cols: 2
    
    AnalogClock:
        id: clock
        started: True
    
    Label:
        text: "Eureka!"
    
    Label:
        text: "The widget AnalogClock is completely modular and works great!!!"
        text_size: self.size
        halign: "center"
        valign: "middle"
    
    Label:
        markup: True
        text: "The [b]widget[/b] [color=#FF0000]works[/color] great!!!"
    
